dataset_roots:
  ESD: ../data/ESD
  RAVDESS: ../data/RAVDESS
  IEMOCAP: ../data/IEMOCAP
  CREMA-D: ../data/CREMA-D

raw_dataset_roots:
  ESD: ../raw_data/ESD
  RAVDESS: ../raw_data/RAVDESS
  IEMOCAP: ../raw_data/IEMOCAP_full_release
  CREMA-D: ../raw_data/CREMA-D

indextts2:
  seed: 42
  root: ../../third_party/IndexTTS
  checkpoint_dir: ../../checkpoints/IndexTTS/IndexTTS-2
  config: ../../checkpoints/IndexTTS/IndexTTS-2/config.yaml
  device: cuda:0
  use_fp16: false
  use_cuda_kernel: false
  use_deepspeed: false
  use_qwen_emo: false
